name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install elan 🕑
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
        ~/.elan/bin/lean --version
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    - name: Install Dependencies
      run: sudo apt-get install alsa libasound2-dev libudev-dev xorg-dev libglu1-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
